### ISSUE TITLE
Currency editing returning error if main is null

### ISSUE THREAD

**Issue by evertramos** [LaravelDaily/Larancer-QuickAdminPanel#1]
There is an error when editing the main currency...

Always when you edit the currency it brings the "main checkbox" false. 

If you let all main currency as false, on the next time you try to check as true it will cause an error:

>ErrorException in CurrenciesController.php line 73: 
>Creating default object from empty value

**Comment by ModestasV** [comment]
Hey, thanks for the report!

There will be fix coming in the next 24 hours!
